"""
AgentState — the single object that flows through every node in the
LangGraph graph.

One AgentState instance is created per user question and mutated as it
passes through plan → execute → evaluate → respond. The retry edge from
evaluate back to plan works by incrementing attempt_count and appending
to failure_history — the plan node reads both to craft a better prompt.

Design notes:
- All fields have defaults so nodes can be tested in isolation without
  constructing a fully-populated state.
- `dataframe_pickle_path` is set once at graph entry and never changed.
- `conversation_history` holds the compressed + recent turns injected
  into the prompt by the context manager. It is NOT the raw chat log.
- `final_answer` is only populated by the respond node; all other nodes
  leave it as None.
"""

from __future__ import annotations

from typing import Literal, Optional, TypedDict

from src.agent.tools.code_executor import ExecutionResult
from src.agent.validators.output_validator import ValidationOutcome


# total=True (default): every key is required. All keys are always set by
# make_initial_state. Fields whose runtime value can be None use Optional[...]
# to express that — absence-from-dict and None-valued are separate concepts.
# Individual graph nodes read only the fields they own; they never construct
# a partial AgentState from scratch, so total=True is safe and accurate.
class AgentState(TypedDict):
    # ------------------------------------------------------------------
    # Inputs (set at graph entry, read-only throughout)
    # ------------------------------------------------------------------

    # The user's natural language question for this turn
    question: str

    # Absolute path to the pickled DataFrame on disk
    # Set once by the graph entry point, never mutated
    dataframe_pickle_path: str

    # ------------------------------------------------------------------
    # Plan node outputs
    # ------------------------------------------------------------------

    # The Python code most recently generated by the LLM
    generated_code: str

    # ------------------------------------------------------------------
    # Execute node outputs
    # ------------------------------------------------------------------

    # Full result from the most recent sandbox execution
    execution_result: Optional[ExecutionResult]

    # ------------------------------------------------------------------
    # Evaluate node outputs
    # ------------------------------------------------------------------

    # Full outcome from the most recent OutputValidator run
    validation_outcome: Optional[ValidationOutcome]

    # ------------------------------------------------------------------
    # Retry tracking (shared between evaluate and plan)
    # ------------------------------------------------------------------

    # Number of plan+execute+evaluate cycles completed so far (0-indexed)
    attempt_count: int

    # Ordered list of (attempt_index, failure_type_str, retry_instruction)
    # The plan node appends the latest entry to its prompt on each retry
    failure_history: list[tuple[int, str, str]]

    # ------------------------------------------------------------------
    # Clarification (set by plan node before code generation)
    # ------------------------------------------------------------------

    # If True, the agent surfaced a clarifying question this turn
    # and did not attempt code generation
    needs_clarification: bool

    # The clarifying question shown to the user (empty if not needed)
    clarifying_question: str

    # ------------------------------------------------------------------
    # Respond node outputs
    # ------------------------------------------------------------------

    # The fully formatted answer returned to the user.
    # None until the respond node runs.
    final_answer: Optional[str]

    # The type of answer produced. Empty string = not yet determined.
    # Used for MLflow logging.
    answer_type: Literal["table", "plot", "text", "error", "clarification", ""]

    # ------------------------------------------------------------------
    # Context (managed by context_manager, injected into prompt_builder)
    # ------------------------------------------------------------------

    # Compressed + windowed conversation history ready for prompt injection.
    # Format: list of {"role": "user"|"assistant", "content": str}
    # Older turns are compressed to single-line summaries by context_manager.
    conversation_history: list[dict]


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

def make_initial_state(
    question: str,
    dataframe_pickle_path: str,
    conversation_history: Optional[list[dict]] = None,
) -> AgentState:
    """
    Create a fresh AgentState for a new question.

    Called once per user turn at the graph entry point. All retry
    counters and intermediate results are initialised to clean defaults.

    Parameters
    ----------
    question:
        The user's natural language question.
    dataframe_pickle_path:
        Absolute path to the pickled DataFrame. Must exist on disk.
    conversation_history:
        Compressed conversation history from context_manager.
        Pass None or [] for the first turn.
    """
    return AgentState(
        question=question,
        dataframe_pickle_path=dataframe_pickle_path,
        generated_code="",
        execution_result=None,
        validation_outcome=None,
        attempt_count=0,
        failure_history=[],
        needs_clarification=False,
        clarifying_question="",
        final_answer=None,
        answer_type="",
        conversation_history=conversation_history or [],
    )